version: '3.8'

services:
  nestjs_aws_starter_db:
    container_name: nestjs_aws_starter_db
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=nestjs_aws_starter_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - LANG=en_US.utf8
      - TZ=UTC

  nestjs_aws_starter_app:
    build: .
    container_name: nestjs_aws_starter_app
    restart: unless-stopped
    depends_on:
      - nestjs_aws_starter_db
    environment:
      DB_HOST: nestjs_aws_starter_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: nestjs_aws_starter_db
    ports:
      - '3333:3333'
